# Generated by Django 5.1.6 on 2025-03-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите аватарку",
                null=True,
                upload_to="",
                verbose_name="Аватар",
            ),
        ),
    ]
