# Generated by Django 5.1.6 on 2025-03-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата последнего входа"
            ),
        ),
    ]
